config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  devise_for :users
  
  root to: 'lifts#index'

  resources :lifts, only: [ :index ] do
    member do 
      put 'favorite' => 'lifts#favorite_lift'
      put 'alert' => 'lifts#alert_lift'
    end
  end

  resources :about, only: [ :index ]

  resources :webcams, only: [ :index ]
    
  authenticated :user, -> user { user.admin? }  do
    mount DelayedJobWeb, at: "/delayed_job"
  end

end

app/models/alert.rb
class Alert < ApplicationRecord
  validates :lift_code, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avalanche.rb
class Avalanche < ApplicationRecord
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ActiveRecord::Base
  extend ActsAsFavoritor::FavoritorLib
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update(blocked: true)
  end
end

app/models/forecast.rb
class Forecast < ApplicationRecord
end

app/models/lift.rb
class Lift < ApplicationRecord
  acts_as_favoritable
  validates :lift_code, uniqueness: true
end

app/models/status.rb
class Status < ApplicationRecord
  after_create :send_alerts

  private
  def send_alerts
    if self.status.upcase == "O"
      lift_id = Lift.where(lift_code: self.lift_code).first.id
      
      # Remove delay job due to AWS issues
      # SendLiftAlertJob.perform_later(lift_id)

      users_to_alert = Favorite.where({favoritable_type: "Alert", favoritable_id: lift_id})
    
      lift_name = Lift.find(lift_id).name
  
      if users_to_alert.length > 0
        users_to_alert.each do |user|
        notify_user = User.find(user.favoritor_id)
  
        # Send SMS to user
        sms = Aws::SNS::Client.new(
          region: ENV["AWS_REGION"],
          access_key_id: ENV["AWS_ACCESS_KEY_ID"],
          secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"])
  
        sms.publish(phone_number: notify_user.phone, 
                    message: "#{lift_name} is open! Full site: www.liveliftinfo.com")
  
        # Delete all user row from Favorite table
        Favorite.where({favoritable_type: "Alert", favoritor_id: user.favoritor_id, favoritable_id: lift_id}).first.delete
        end
        puts "<<< Sent SMS Alerts For #{lift_name} >>> \n\n"
      end  
      puts "<<< No SMS Alerts Sent For #{lift_name} >>> \n\n"
    end 
  end

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_favoritor

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  before_validation :strip_non_numeric

  validates :phone, phone: { possible: true, types: :mobile, countries: [:us, :ca], sanitized: true }

  def strip_non_numeric
    self.phone = phone.gsub(/\D/, '')
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def retrieve_lift_status(lift)
    status = Status.where(lift_code: lift.lift_code).last&.status&.upcase

    if status == "O"
      "status_icons/open.svg"
    elsif status == "H"
      "status_icons/hold.svg"
    else
      "status_icons/closed.svg"
    end
  end
  helper_method :retrieve_lift_status

  def string_to_date(string)
    DateTime.parse(string).strftime("%B %d, %Y")
  end
  helper_method :string_to_date

  def retrieve_lift_image(lift_type) 
    if lift_type == "T"
      "lift_icons/rope_tow.svg"
    elsif lift_type == "3"
      "lift_icons/three_p_chair.svg"
    elsif lift_type == "4"
      "lift_icons/four_p_chair.svg"
    elsif lift_type == "6"
      "lift_icons/six_p_chair.svg"
    else
      "lift_icons/gondola.svg"
    end
  end
  helper_method :retrieve_lift_image

  def avalanche_background_color(danger_rating)
    if danger_rating == "1"
      "background-color: #7bb24b"
    elsif danger_rating == "2"
      "background-color: #ffed47"
    elsif danger_rating == "3"
      "background-color: #e39446"
    elsif danger_rating == "4"
      "background-color: #d65345"
    else
      "background-color: #000000"
    end
  end
  helper_method :avalanche_background_color

  def retrieve_weather_image(weather_description)
    description = weather_description.downcase
    if description == "fairpartlycloudy" || description == "mostlysunny"
      "weather_icons/partly_cloudy.svg"
    elsif description == "sunny"
      "weather_icons/sunny.svg"
    elsif description == "cloudy" || description == "mostlycloudy"
      "weather_icons/cloudy.svg"
    elsif description == "rain"
      "weather_icons/rain.svg"
    elsif description == "showers"
      "weather_icons/rain_showers.svg"
    elsif description == "snowshowers"
      "weather_icons/snow_showers.svg"
    elsif description == "snow"
      "weather_icons/snow.svg"
    else
      "weather_icons/weather_generic.svg"
    end
  end
  helper_method :retrieve_weather_image

  def favorite_exists(lift_id, id)
    f = Favorite.where({favoritable_type: "Lift", favoritable_id: lift_id, favoritor_id: id })
    f.length > 0 ? true : false
  end
  helper_method :favorite_exists

  def alert_exists(lift_id, id)
    a = Favorite.where({favoritable_type: "Alert", favoritable_id: lift_id, favoritor_id: id })
    a.length > 0 ? true : false
  end
  helper_method :alert_exists

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:phone])
  end
end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController
  before_action :authenticate_user!, only: [ :favorite_lift, :alert_lift ]
  before_action :find_lift, only: [ :favorite_lift ]
  before_action :find_alert, only: [ :alert_lift ]
  respond_to :js, :json, :html


  def index
    @lifts = Lift.all
    @blackcomb_lifts = @lifts.slice(0, 15)
    @whistler_lifts = @lifts.drop(15)
    @weather = Forecast.last
    @avalanche = Avalanche.last
    @history = Status.where("created_at::date > ?", (Date.today - 7))
    @favorites = Favorite.where({favoritable_type: "Lift", favoritor_id: current_user&.id})
    @alerts = Favorite.where({favoritable_type: "Alert", favoritor_id: current_user&.id})
  end

  def favorite_lift
    if !current_user.favorited? @lift
      current_user.favorite @lift
    elsif current_user.favorited? @lift
      current_user.remove_favorite @lift
    end    
  end

  def alert_lift
    if !current_user.favorited? @alert
      current_user.favorite @alert
    elsif current_user.favorited? @alert
      current_user.remove_favorite @alert
    end    
  end

  private
  def find_lift
    @lift = Lift.find_by(id: params[:id])
  end

  def find_alert
    @alert = Alert.find_by(id: params[:id])
  end
end

app/controllers/webcams_controller.rb
class WebcamsController < ApplicationController
  def index
    render "lifts/webcam_partials/_cam_collapse",
           layout: false
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed:
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/lifts_helper.rb
module LiftsHelper
end

app/helpers/webcams_helper.rb
module WebcamsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <% if type == "notice" && message == "You will receive an email with instructions on how to reset your password in a few minutes." %>
    <div class="alert alert-warning %> alert-dismissible fade show mt-2" role="alert">
  <% elsif type == "notice" %>
    <div class="alert alert-success %> alert-dismissible fade show mt-2" role="alert">
  <% else %>
    <div class="alert alert-<%= type %> alert-dismissible fade show mt-2" role="alert">
  <% end %>
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/lifts/_blackcomb_favorites.html.erb
<div class="panel-group lift-list mr-auto" id="accordion-blackcomb-all" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading p-1" role="tab" id="heading-blackcomb-all">
      <h4 class="panel-title my-auto">
        <a class="pl-3" role="button" data-toggle="collapse" data-parent="#accordion-blackcomb-all" href="#collapse-blackcomb-all" aria-expanded="true" aria-controls="collapse-blackcomb-all">
          Blackcomb Mountain
        </a>
      </h4>
    </div>
    <div id="collapse-blackcomb-all" class="panel-collapse collapse show" role="tabpanel" aria-labelledby="heading-blackcomb-all">
      <div class="panel-body">
        <div class="panel-group pl-2" id="accordion-blackcomb-lifts-all" role="tablist" aria-multiselectable="true">
          <!-- Render a panel for each Blackcomb list -->
          <% @blackcomb_lifts.each do |lift| %>
          <% if favorite_exists(lift.id, current_user.id) || alert_exists(lift.id, current_user.id) %>
            <div class="panel panel-default p-1 border-top">
              <div class="panel-heading" role="tab" id="heading-<%= lift.lift_code %>-all">
                <div class="row">
                  <div class="col-8 lift-col my-auto">
                    <h5 class="panel-title">
                      <a class="pl-4 lift-panel-heading text-nowrap" role="button" data-toggle="collapse" data-parent="#accordion-blackcomb-lifts-all" href="#collapse-<%= lift.lift_code %>-all" aria-expanded="false" aria-controls="collapse-<%= lift.lift_code %>-all">
                        <%= lift.name %>
                      </a>
                    </h5>
                  </div>
                  <div class="col-xs-12 col-sm-4 lift-col-right d-flex pr-5 justify-content-end">
                    <%= image_tag("#{retrieve_lift_status(lift)}", class: "lift-status img-fluid border rounded mr-2") %>
                    <% if user_signed_in? %>
                      <% if favorite_exists(lift.id, current_user.id) %>
                        <%= link_to favorite_lift_path(lift), class: "btn btn-warning favorite mr-2 pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/favorite_null.svg", class: "favorite-icon img-fluid") %>
                        <% end %>
                      <% else %>
                        <%= link_to favorite_lift_path(lift), class: "btn btn-warning no-favorite mr-2 pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/favorite_null.svg", class: "favorite-icon img-fluid") %>
                        <% end %>
                      <% end %>
                      
                      <% if alert_exists(lift.id, current_user.id) %>
                        <%= link_to alert_lift_path(lift), class: "btn btn-danger alerted pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/alert_null.svg", class: "alert-icon img-fluid") %>
                        <% end %>
                      <% else %>
                        <%= link_to alert_lift_path(lift), class: "btn btn-danger no-alert pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/alert_null.svg", class: "alert-icon img-fluid") %>
                        <% end %>
                      <% end %>
                    <% else %>
                      <a href="#" class="btn btn-outline-warning disabled no-favorite pt-2">
                        <%= image_tag("general_icons/favorite_null.svg", class: "favorite-icon img-fluid") %>
                      </a>
                      <a href="#" class="btn btn-outline-danger disabled pt-2">
                        <%= image_tag("general_icons/alert_null.svg", class: "alert-icon img-fluid") %>
                      </a>
                    <% end %>
                  </div>
                </div>
              </div>
              <div id="collapse-<%= lift.lift_code %>-all" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-<%= lift.lift_code %>-all">
                <div class="panel-body">
                  <%= render partial: "lifts/lift_show", locals: {lift: lift} %>
                </div>
              </div>
            </div>
          <% end %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/lifts/_blackcomb_lift_status.html.erb
<div class="panel-group lift-list mr-auto" id="accordion-blackcomb-all" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading p-1" role="tab" id="heading-blackcomb-all">
      <h4 class="panel-title my-auto">
        <a class="pl-3" role="button" data-toggle="collapse" data-parent="#accordion-blackcomb-all" href="#collapse-blackcomb-all" aria-expanded="false" aria-controls="collapse-blackcomb-all">
          Blackcomb Mountain
        </a>
      </h4>
    </div>
    <div id="collapse-blackcomb-all" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-blackcomb-all">
      <div class="panel-body">
        <div class="panel-group pl-2" id="accordion-blackcomb-lifts-all" role="tablist" aria-multiselectable="true">
          <!-- Render a panel for each Blackcomb list -->
          <% @blackcomb_lifts.each do |lift| %>
            <div class="panel panel-default p-1 border-top">
              <div class="panel-heading" role="tab" id="heading-<%= lift.lift_code %>-all">
                <div class="row">
                  <div class="col-8 lift-col my-auto">
                    <h5 class="panel-title">
                      <a class="pl-4 lift-panel-heading text-nowrap" role="button" data-toggle="collapse" data-parent="#accordion-blackcomb-lifts-all" href="#collapse-<%= lift.lift_code %>-all" aria-expanded="false" aria-controls="collapse-<%= lift.lift_code %>-all">
                        <%= lift.name %>
                      </a>
                    </h5>
                  </div>
                  <div class="col-xs-12 col-sm-4 lift-col-right d-flex pr-5 justify-content-end justify-content-xs-center">
                    <%= image_tag("#{retrieve_lift_status(lift)}", class: "lift-status img-fluid border rounded mr-2") %>
                    <% if user_signed_in? %>
                      <% if favorite_exists(lift.id, current_user.id) %>
                        <%= link_to favorite_lift_path(lift), class: "btn btn-warning favorite mr-2 pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/favorite_null.svg", class: "favorite-icon img-fluid") %>
                        <% end %>
                      <% else %>
                        <%= link_to favorite_lift_path(lift), class: "btn btn-warning no-favorite mr-2 pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/favorite_null.svg", class: "favorite-icon img-fluid") %>
                        <% end %>
                      <% end %>
                      
                      <% if alert_exists(lift.id, current_user.id) %>
                        <%= link_to alert_lift_path(lift), class: "btn btn-danger alerted pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/alert_null.svg", class: "alert-icon img-fluid") %>
                        <% end %>
                      <% else %>
                        <%= link_to alert_lift_path(lift), class: "btn btn-danger no-alert pt-2", method: :put, remote: :true do %>
                           <%= image_tag("general_icons/alert_null.svg", class: "alert-icon img-fluid") %>
                        <% end %>
                      <% end %>
                    <% else %>
                      <span class="d-inline-flex mr-2 span-height" tabindex="0" data-toggle="tooltip" title="Sign in to create a favorite!">
                        <a href="#" class="btn btn-outline-warning disabled pt-2">
                          <%= image_tag("general_icons/favorite_null.svg", class: "favorite-icon img-fluid") %>
                        </a>
                      </span>
                      <span class="d-inline-flex span-height" tabindex="0" data-toggle="tooltip" title="Sign in to set an SMS alert!">
                        <a href="#" class="btn btn-outline-danger disabled pt-2">
                          <%= image_tag("general_icons/alert_null.svg", class: "alert-icon img-fluid") %>
                        </a>
                      </span>
                    <% end %>
                  </div>
                </div>
              </div>
              <div id="collapse-<%= lift.lift_code %>-all" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-<%= lift.lift_code %>-all">
                <div class="panel-body">
                  <%= render partial: "lifts/lift_show", locals: {lift: lift} %>
                </div>
              </div>
            </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/lifts/_weather_forecast.html.erb
<div class="container">
  <div class="row justify-content-around">
    <% 6.times do |day| %>
      <div class="col-xs-6 col-sm-4 col-xl-3 m-4">
        <div class="row font-weight-bold justify-content-center mb-1">
          <%= @weather.forecast[day]["dayDescription"] %>
        </div>
        <div class="col border border-dark rounded weather-image mx-auto mb-1">
          <%= image_tag("#{retrieve_weather_image(@weather.forecast[day]["iconName"])}", class: "weather-image h-90 img-fluid mx-auto d-block p-3") %>
        </div>
        <div class="col">
          <div class="row justify-content-center">
            <strong class="w-100 text-center">Description</strong>
            <span class="text-center">
              <%= @weather.forecast[day]["summaryDescription"] %>
            </span>
          </div>
          <div class="toggle-unit no-show row justify-content-around">
            <span>
              <strong>High:</strong> <%= @weather.forecast[day]["temperatureHigh"] %> °F
            </span>
            <span>
              <strong>Low:</strong> <%= @weather.forecast[day]["temperatureLow"] %> °F
            </span>
          </div>
          <div class="toggle-unit show row justify-content-around">
            <span>
              <strong>High:</strong> <%= ((@weather.forecast[day]["temperatureHigh"].to_i - 32) * 5/9) %> °C
            </span>
            <span>
              <strong>Low:</strong> <%= ((@weather.forecast[day]["temperatureLow"].to_i - 32) * 5/9) %> °C
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row justify-content-center pb-3">
    <div class="row w-100 align-items-center justify-content-center">
      <%= image_tag("general_icons/external_link.svg", class: "external-link img-fluid mr-1") %>
      <span class="external-link-span">
        <%= link_to "Resort Weather Forecast", "https://www.whistlerblackcomb.com/the-mountain/mountain-conditions/snow-and-weather-report.aspx", target: :_blank, rel: "noopener", class: "pb-1" %>
      </span>
    </div>
    <div class="row w-100 align-items-center justify-content-center">
        <%= image_tag("general_icons/external_link.svg", class: "external-link img-fluid mr-1") %>
      <span class="external-link-span">
        <%= link_to "Environment Canada Weather Forecast", "https://weather.gc.ca/city/pages/bc-86_metric_e.html", target: :_blank, rel: "noopener", class: "pb-1" %>
      </span>
    </div>
  </div>
</div>

app/views/lifts/_whistler_favorites.html.erb
<div class="panel-group lift-list" id="accordion-whistler-all" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading p-1" role="tab" id="heading-whistler-all">
      <h4 class="panel-title my-auto">
        <a class="pl-3" role="button" data-toggle="collapse" data-parent="#accordion-whistler-all" href="#collapse-whistler-all" aria-expanded="true" aria-controls="collapse-whistler-all">
          Whistler Mountain
        </a>
      </h4>
    </div>
    <div id="collapse-whistler-all-favorites" class="panel-collapse collapse show" role="tabpanel" aria-labelledby="heading-whistler-all">
      <div class="panel-body">
        <div class="panel-group" id="accordion-whistler-lifts-all" role="tablist" aria-multiselectable="true">
          <!-- Render a panel for each whistler list -->
          <% @whistler_lifts.each do |lift| %>
          <% if favorite_exists(lift.id, current_user.id) || alert_exists(lift.id, current_user.id) %>
            <div class="panel panel-default p-1 border-top">
              <div class="panel-heading" role="tab" id="heading-<%= lift.lift_code %>-all">
                <div class="row pl-2">
                  <div class="col-8 lift-col my-auto">
                    <h5 class="panel-title">
                      <a class="pl-4 lift-panel-heading text-nowrap" role="button" data-toggle="collapse" data-parent="#accordion-whistler-lifts-all" href="#collapse-<%= lift.lift_code %>-all" aria-expanded="false" aria-controls="collapse-<%= lift.lift_code %>-all">
                        <%= lift.name %>
                      </a>
                    </h5>
                  </div>
                  <div class="col-xs-12 col-sm-4 lift-col-right d-flex pr-5 justify-content-end">
                    <%= image_tag("#{retrieve_lift_status(lift)}", class: "lift-status img-fluid border rounded mr-2") %>
                    <% if user_signed_in? %>
                      <% if favorite_exists(lift.id, current_user.id) %>
                        <%= link_to favorite_lift_path(lift), class: "btn btn-warning favorite mr-2 pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/favorite_null.svg", class: "favorite-icon img-fluid") %>
                        <% end %>
                      <% else %>
                        <%= link_to favorite_lift_path(lift), class: "btn btn-warning no-favorite mr-2 pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/favorite_null.svg", class: "favorite-icon img-fluid") %>
                        <% end %>
                      <% end %>
                      
                      <% if alert_exists(lift.id, current_user.id) %>
                        <%= link_to alert_lift_path(lift), class: "btn btn-danger alerted pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/alert_null.svg", class: "alert-icon img-fluid") %>
                        <% end %>
                      <% else %>
                        <%= link_to alert_lift_path(lift), class: "btn btn-danger no-alert pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/alert_null.svg", class: "alert-icon img-fluid") %>
                        <% end %>
                      <% end %>
                    <% else %>
                      <a href="#" class="btn btn-outline-warning disabled no-favorite mr-2 pt-2">
                        <%= image_tag("general_icons/favorite_null.svg", class: "favorite-icon img-fluid") %>
                      </a>
                      <a href="#" class="btn btn-outline-danger disabled pt-2">
                        <%= image_tag("general_icons/alert_null.svg", class: "alert-icon img-fluid") %>
                      </a>
                    <% end %>



                  </div>  
                </div>
              </div>
              <div id="collapse-<%= lift.lift_code %>-all" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-<%= lift.lift_code %>-all">
                <div class="panel-body">
                  <%= render partial: "lifts/lift_show", locals: {lift: lift} %>
                </div>
              </div>
            </div>
          <% end %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/lifts/_whistler_lift_status.html.erb
<div class="panel-group lift-list" id="accordion-whistler-all" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading p-1" role="tab" id="heading-whistler-all">
      <h4 class="panel-title my-auto">
        <a class="pl-3" role="button" data-toggle="collapse" data-parent="#accordion-whistler-all" href="#collapse-whistler-all" aria-expanded="false" aria-controls="collapse-whistler-all">
          Whistler Mountain
        </a>
      </h4>
    </div>
    <div id="collapse-whistler-all" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-whistler-all">
      <div class="panel-body">
        <div class="panel-group" id="accordion-whistler-lifts-all" role="tablist" aria-multiselectable="true">
          <!-- Render a panel for each whistler list -->
          <% @whistler_lifts.each do |lift| %>
            <div class="panel panel-default p-1 border-top">
              <div class="panel-heading" role="tab" id="heading-<%= lift.lift_code %>-all">
                <div class="row">
                  <div class="col-8 lift-col my-auto">
                    <h5 class="panel-title">
                      <a class="pl-4 lift-panel-heading text-nowrap" role="button" data-toggle="collapse" data-parent="#accordion-whistler-lifts-all" href="#collapse-<%= lift.lift_code %>-all" aria-expanded="false" aria-controls="collapse-<%= lift.lift_code %>-all">
                        <%= lift.name %>
                      </a>
                    </h5>
                  </div>
                  <div class="col-xs-12 col-sm-4 lift-col-right d-flex pr-5 justify-content-end">
                    
                    <%= image_tag("#{retrieve_lift_status(lift)}", class: "lift-status img-fluid border rounded mr-2") %>
                    <% if user_signed_in? %>
                      <% if favorite_exists(lift.id, current_user.id) %>
                        <%= link_to favorite_lift_path(lift), class: "btn btn-warning favorite mr-2 pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/favorite_null.svg", class: "favorite-icon img-fluid") %>
                        <% end %>
                      <% else %>
                        <%= link_to favorite_lift_path(lift), class: "btn btn-warning no-favorite mr-2 pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/favorite_null.svg", class: "favorite-icon img-fluid") %>
                        <% end %>
                      <% end %>
                      
                      <% if alert_exists(lift.id, current_user.id) %>
                        <%= link_to alert_lift_path(lift), class: "btn btn-danger alerted pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/alert_null.svg", class: "alert-icon img-fluid") %>
                        <% end %>
                      <% else %>
                        <%= link_to alert_lift_path(lift), class: "btn btn-danger no-alert pt-2", method: :put, remote: :true do %>
                          <%= image_tag("general_icons/alert_null.svg", class: "alert-icon img-fluid") %>
                        <% end %>
                      <% end %>
                    <% else %>
                      <span class="d-inline-flex mr-2 span-height" tabindex="0" data-toggle="tooltip" title="Sign in to create a favorite!">
                        <a href="#" class="btn btn-outline-warning disabled no-favorite pt-2">
                          <%= image_tag("general_icons/favorite_null.svg", class: "favorite-icon img-fluid") %>
                        </a>
                      </span>
                      <span class="d-inline-flex span-height" tabindex="0" data-toggle="tooltip" title="Sign in to set an SMS alert!">
                        <a href="#" class="btn btn-outline-danger disabled pt-2">
                          <%= image_tag("general_icons/alert_null.svg", class: "alert-icon img-fluid") %>
                        </a>
                      </span>
                    <% end %>

                  </div>  
                </div>
              </div>
              <div id="collapse-<%= lift.lift_code %>-all" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-<%= lift.lift_code %>-all">
                <div class="panel-body">
                  <%= render partial: "lifts/lift_show", locals: {lift: lift} %>
                </div>
              </div>
            </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>